### ISSUE TITLE
MeshPolicy does not get converted to respective correct RequestAuthentication

### ISSUE THREAD

**Issue by aliabbasjaffri** [istio-ecosystem/security-policy-migrate#8]
We had the following MeshPolicy which we were trying to migrate to the `istio` v1.6.0
```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
  originIsOptional: true
  origins:
  - jwt:
      issuer: "https://keycloak.domain"
      jwksUri: "https://keycloak.domain/protocol/openid-connect/certs"
      jwt_headers:
        - "x-amzn-oidc-accesstoken"
  principalBinding: USE_ORIGIN
```
The migration was attempted using the security-policy-migrate tool, and it generated the following `PeerAuthentication` and `RequestAuthentication` yamls.

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  annotations:
    security.istio.io/alpha-policy-convert: converted from alpha authentication policy
      /default, mesh level policy
  creationTimestamp: null
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  annotations:
    security.istio.io/alpha-policy-convert: converted from alpha authentication policy
      /default, mesh level policy
  creationTimestamp: null
  name: default
  namespace: istio-system
spec:
  jwtRules:
  - fromHeaders:
    - name: x-amzn-oidc-accesstoken
    issuer: https://keycloak.domain
    jwksUri: https://keycloak.domain/protocol/openid-connect/certs
---
```

Unfortunately the generated v1beta1 `RequestAuthentication` policy didn't work. After a lot of debugging and trial and error, i finally found that the missing piece was `forwardOriginalToken: true` from `RequestAuthentication`. To my frustration, this change/requirement was nowhere documented and took a lot of time to figure it out. I am creating a bug here, so that this can be resolved, and if someone else stumbles over the same issue, they know what to do.
